
export const FLOW_ROUTES = {
  home: "/",
  chooseType: "/Client/choose-type",
  ringStyle: "/Client/ringstyle",
  necklace: "/Client/necklace",
  braclet: "/Client/braclet",
  earings: "/Client/earings",
  chooseGender: "/Client/choose-gender",
  chooseGem: "/Client/choose-gem",
  chooseMetal: "/Client/choose-metal",
  chooseSize: "/Client/choose-size",
  GemDecision: "/Client/Gem",
  StoneColor: "/Client/stoneColor",
  StoneDetail: "/Client/stone-detail",
  PickOption: "/Client/pick",
  yss: "/Client/yss",
  additionalDetails: "/Client/additional-details",
  additionalStyle: "/Client/additional-style",
  imagePreview: "/Client/ImagePreview",
  wearFrequency: "/Client/wear-frequency",
  preferSetting: "/Client/prefer-setting",
  personalPreferences: "/Client/personal-preferences",
  setting: "/Client/setting",
  inspirationImage: "/Client/inspiration-image",
} as const
